### ISSUE TITLE
MaxLenth negativo para VarChar(max)

### ISSUE THREAD

**Issue by loxorolim** [stone-payments/StrangerData#41]
Se eu tenho um varchar(max) ele crasha na hora de montar o valor. O MaxLength dele fica como -1 e crasha nessa função aqui: 

Any.String(columnInfo.MaxLength);

**Comment by rengenesio** [comment]
Repro steps:

- Create a table containing a `VARCHAR(MAX)` column on SQL Server database: `CREATE TABLE TestTable (UnlimitedColumn ARCHAR(MAX) NOT NULL)`
- Execute code: `var mockedData = new DataFactory<SqlServerDialect>({DatabaseConnectionString}).CreateOne("TestTable");`
- Expected behaviour: Method executes successfully, inserts a random value for `UnlimitedColumn` on `TestTable` and `mockedData` containing the value.
- Current behaviour: exception is thrown:
```
System.Exception
Could not generate value for column Name=[UnlimitedColumn] Type=[String]
   at StrangerData.Utils.RandomValues.ForColumn(TableColumnInfo columnInfo)
   at StrangerData.Generator.TableGenerator.GenerateValues()
   at StrangerData.DataFactory`1.CreateOne(String tableName)
   at 
---
Local code stack trace ommited
---

System.ArgumentOutOfRangeException
Specified argument was out of the range of valid values.
Parameter name: count
   at System.Linq.Enumerable.Repeat[TResult](TResult element, Int32 count)
   at StrangerData.Any.String(Int32 length)
   at StrangerData.Utils.RandomValues.GenerateForColumn(TableColumnInfo columnInfo)
   at StrangerData.Utils.RandomValues.ForColumn(TableColumnInfo columnInfo)
```
